# Generated by Django 5.1.6 on 2025-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('geo_coordinates', models.CharField(max_length=200)),
                ('proof', models.ImageField(upload_to='proofs/')),
                ('confirmation', models.ImageField(upload_to='confirmations/')),
                ('alert_addressed', models.BooleanField(default=False)),
                ('alert_zone', models.IntegerField()),
            ],
        ),
    ]
