# Generated by Django 5.1.6 on 2025-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='confirmation',
            field=models.ImageField(blank=True, null=True, upload_to='confirmations/'),
        ),
    ]
