# Generated by Django 5.1.6 on 2025-02-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_logger', '0002_alter_message_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='alert_zone',
        ),
    ]
